name: CMake Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash    
    steps:
      - uses: Actions/checkout@v1
      - name: Print workspace path
        run:
          echo "Runner Workspace path is ${{runner.workspace}}"
          echo "GITHUB_WORKSPACE path is $GITHUB_WORKSPACE"

      - name: Configure CMake
        run:           
          cmake -S $GITHUB_WORKSPACE/tests/smarttests/ -B ${{runner.workspace}}/build

      - name: Build
        working-directory: ${{runner.workspace}}/build
        run:           
          cmake --build .

      - name: Test
        working-directory: ${{runner.workspace}}/build
        run: 
          GTEST_OUTPUT=xml:${{runner.workspace}}/build/test-results GTEST_COLOR=1 ctest -V                
      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Archive shared objects
          path: ${{runner.workspace}}/build/**/*.so

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            ${{runner.workspace}}/build/**/*.xml
            ${{runner.workspace}}/build/**/*.trx
            ${{runner.workspace}}/build/**/*.json    
    